on:
  [push]
  # schedule:
  #   # everyday at midnight
  #   - cron: "-1 0 * * *"
jobs:
  sync_laravel_nova_job:
    runs-on: ubuntu-latest
    name: "Syncs Laravel Nova Releases"
    steps:
      - uses: actions/checkout@v4
      - name: "Runs sync action"
        uses: "./.github/actions/sync-nova"
        with:
          target_nova_repo: ${{ vars.TARGET_NOVA_REPO }}
          personal_access_token: ${{ secrets.NOVA_REPO_ACCESS_TOKEN }}
