on:
  [push]
  # schedule:
  #   # everyday at midnight
  #   - cron: "-1 0 * * *"
jobs:
  sync_laravel_nova_job:
    runs-on: ubuntu-latest
    name: "Syncs Laravel Nova Releases"
    steps:
      - uses: actions/checkout@v4

      - name: "Runs sync action"
        id: "releases"
        uses: "./.github/actions/sync-nova"
        with:
          target_nova_repo: ${{ vars.TARGET_NOVA_REPO }}
          personal_access_token: ${{ secrets.NOVA_REPO_ACCESS_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.TARGET_NOVA_REPO }}
          token: ${{ secrets.NOVA_REPO_ACCESS_TOKEN }}

      - name: "Create branch and commit changes"
        env:
          nova_user: ${{ secrets.NOVA_USER }}
          nova_password: ${{ secrets.NOVA_4_PASSWORD }}
        run: |
          ls -la
          git config --global user.email "kaspar.rosin@gmail.com"
          git config --global user.name "Kaspar Rosin"
          git checkout -b "${{ steps.releases.outputs.next_release_tag }}"
          git rm -rf .
          AUTH_ENCODED=$(echo "${nova_user}:${nova_password}"| base64)
          wget -d --header="Authorization: Basic ${AUTH_ENCODED}" ${{ steps.release.outputs.nova_dist_url }}
          git add .
          git commit -m "test"
          git push --set-upstream origin ${{ steps.releases.outputs.next_release_tag }} --force
