on:
  [push]
  # schedule:
  #   # everyday at midnight
  #   - cron: "-1 0 * * *"
jobs:
  sync_laravel_nova_job:
    runs-on: ubuntu-latest
    name: "Syncs Laravel Nova Releases"
    steps:
      - uses: actions/checkout@v4

      - name: "Runs sync action"
        id: "releases"
        uses: "./.github/actions/sync-nova"
        with:
          target_nova_repo: ${{ vars.TARGET_NOVA_REPO }}
          personal_access_token: ${{ secrets.NOVA_REPO_ACCESS_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.TARGET_NOVA_REPO }}
          token: ${{ secrets.NOVA_REPO_ACCESS_TOKEN }}

      - name: "Create branch and commit changes"
        run: |
          ls -la
          git checkout -b "${{ steps.releases.outputs.next_release_tag }}"
          rm -rf
          git add .
          git commit -m "test"
          git push --set-upstream origin ${{ steps.releases.outputs.next_release_tag }}
